### PR TITLE
Publishing to Hash-Archive.org

### PR DESCRIPTION
**Pull request by btrask**
I should've broken this commit down a bit more, sorry. It does a few things:

1. Moves Twitter logic into twitter.py
2. Adds #!s for addurl.py and minitrue.py
3. Adds hasharchive.py which simply submits all URLs to hash-archive.org

I can rework the changes if you don't like it.

### CODE REVIEW

**Comment by paultopia** [comment]
This looks great.  There's just one concern: I didn't realize that hash-archive.org allows one to search by hash and get out the url.  But part of the deterrent strategy of minitrue is that possible malefactors don't know which URLs are being monitored; being able to put the hash that got tweeted into a search engine and get out a URL compromises that.  

One obvious solution would be to just use a different algorithm for the tweet than for hash-archive. It looks like hash-archive doesn't do SHA224, so maybe a solution would be to generate that hash as well, store both the 224 and 256 hashes, and tweet the 224 one.  What do you think?  (I suspect you know more about secure hashes than I do, so if you think this is a non-problem, please let me know.)

**Comment by btrask** [comment]
@paultopia: If you want hashes that can't be reversed, the simplest way is to add a salt. Generate and store a random string the first time MiniTrue is run, and then hash it together with each document. That way, it will be impossible for anyone to build a mapping between hashes and URLs, without knowing the salt.

Switching to SHA-224 won't be effective, because anyone can build a database of those hashes too.

**Comment by paultopia** [comment]
That's an excellent point.  I think for now this can be merged, and salting will be a good next project.

**Comment by btrask** [comment]
Cool, thanks!

**Pull request merged**
